experiment_name: vit_base_2025-05-20-2118
imagenet_dir: "${IMAGENET_DIR:-./data/imagenet-1k}"
batch_size: 128
num_workers: 8
num_classes: 1000
gpus: 8
max_epochs: 50
learning_rate: 3e-4
precision: 16
log_every_n_steps: 50
model_type: vit
emb_size: 768
depth: 24
# key difference: 
# depth: 12 -> 24
loss_assignment: all_iterations
warmup_steps: 50000.0