experiment_name: vit_iterative_2025-05-12-2356
imagenet_dir: "/mnt/d1/eirwynliang/imagenet-1k-processed-deepseek"
batch_size: 62
num_workers: 8
num_classes: 1000
gpus: 2
max_epochs: 50
learning_rate: 3e-4
precision: 16
log_every_n_steps: 50
model_type: iterative_vit
num_iterative_tokens: 10
num_iterations: 2
layer_idx: -2
emb_size: 768
# key difference: 
# num_iterations: 2, num_iterative_tokens: 10