experiment_name: vit_iterative_2025-04-06-0134
imagenet_dir: "${IMAGENET_DIR:-./data/imagenet-1k}"
batch_size: 128
num_workers: 8
num_classes: 1000
gpus: 8
max_epochs: 50
learning_rate: 3e-4
precision: 16
log_every_n_steps: 50
model_type: iterative_vit
num_iterative_tokens: 3
num_iterations: 5
layer_idx: -2
emb_size: 768