experiment_name: vit_base_2025-04-06-0134
imagenet_dir: "/mnt/d1/eirwynliang/imagenet-1k-processed-deepseek"
batch_size: 64
num_workers: 8
num_classes: 1000
gpus: 2
max_epochs: 50
learning_rate: 3e-4
precision: 16
log_every_n_steps: 50
use_iterative_vit: false
num_iterative_tokens: 3
num_iterations: 5
layer_idx: -2
emb_size: 768